baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'hugo-blog-theme'

[taxonomies]
  category = 'categories'
  tag      = 'tags'
  series   = 'series'
  author   = 'authors'
